name: kubemin-agent
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - fastapi
      - langchain
      - pydantic-settings
      - python-dotenv
      - sentence-transformers
      - uvicorn[standard]
